### ISSUE TITLE
popupReport will not display correctly with 900+ points

### ISSUE THREAD

**Issue by charleyzhuyi** [Boris-Em/BEMSimpleLineGraph#109]
If there are more than 900 points has been imported to the graph, the popupReport will stop showing up for points more than 900. (however touchInputLine works fine for those points over 900)

The magic number "900" is observed by inspect the value of index through "didTouchGraphWithClosestIndex:(NSInteger)index" delegate; it will not called if drag the chart to points over 900. It seems there is a enum  may contributed such limitation of 900 points; DotLastTag1000 - DotFirstTag100 = 900;

BEMSimpleLineGraphView.m
typedef NS_ENUM(NSInteger, BEMInternalTags)
{
    DotFirstTag100 = 100,
    DotLastTag1000 = 1000,
    LabelYAxisTag2000 = 2000,
    BackgroundYAxisTag2100 = 2100,
    PermanentPopUpViewTag3100 = 3100,
};

Steps to reproduce the issue:

Step One:  open the SimpleLineChart demo, added a for-loop around line 124-125 from:

            [self.arrayOfValues addObject:@([self getRandomInteger])];
            [self.arrayOfDates addObject:[NSString stringWithFormat:@"%i", (int) [[self.arrayOfDates lastObject] integerValue] + 1]];

to:

        for (int i=0; i<1500; i++) {
            [self.arrayOfValues addObject:@([self getRandomInteger])];
            [self.arrayOfDates addObject:[NSString stringWithFormat:@"%i", (int) [[self.arrayOfDates lastObject] integerValue] + 1]];
        }

Step Two: Run it and click "+" button. Wait a few second until the chart reloaded.

Step Three: Drag the chart from left side to right side, you will notice that the popReport stuck at point around 850-900 (different each time depend how fast to drag) , but touchinputLine can still keep moving beyond that point. See attached screenshot.

![ios simulator screen shot nov 24 2014 9 37 41 pm](https://cloud.githubusercontent.com/assets/2998336/5178535/be9e873a-7422-11e4-98bb-d6eb8aba937f.png)

**Comment by Sam-Spencer** [comment]
There are no specific plans to allow the graph to go over 1000 points. If you need more than that, I would recommend averaging some points and displaying less. I am going to close this issue for now. If you feel it should be reopened, please let us know.

**Comment by skuske** [comment]
Any chance that this will be fixed? Or any suggestion for a quick fix (if possible)? Thanks.

**Comment by fukemy** [comment]
you ask the really hard question. I think the solution is only make the viewport and move it to view all data with 10 point / screen.
 sorry for my bad english, just search graph viewport android to know
