### ISSUE TITLE
Unevenly spaced data

### ISSUE THREAD

**Issue by matthewcheok** [Boris-Em/BEMSimpleLineGraph#112]
I'm not sure if there's a solution for this - my data is unevenly spaced in the x-axis. I still want a continuous line through the points.

**Comment by Sam-Spencer** [comment]
PR #129 adds the ability to specify a NULL value. It is currently under review, but it looks like we'll be merging it here in the next few days.

**Comment by Sam-Spencer** [comment]
Pull Request #129 has been merged, and commit 16b1a40a32c81652ddeb0923d3121c8986ceb6f9 should add the requested feature.

Fine-tuned control and positioning is not, and likely will not be, supported by **BEMSimpleLineGraph**. The goal of the project is to remain lightweight and easy to use. Custom data point positioning would break a great deal of things in the project.
