### ISSUE TITLE
Determine x-value of a certain point by a number instead of it's index in the input array?

### ISSUE THREAD

**Issue by sonbui-savvycom** [Boris-Em/BEMSimpleLineGraph#117]
I am using your library and it works very nice!

Now, I determine a point in the line chart by the value in the input data as the y-value and it's index in the input array as the x-value. Then, if I want to use an any number as it's x-value instead of using it's index, how can I do this?

**Comment by Sam-Spencer** [comment]
Currently it is not possible to determine a y-value's x-index. I cannot see a use-case where this would be an applicable feature. If you maintain and keep track of your own data source should this really be necessary?

**Comment by Sam-Spencer** [comment]
Your contribution is appreciated, however this issue will now be closed. Should there be further discussion or questions related to this issue, it can be reopened. Thank you.
