### ISSUE TITLE
NSString methods for y values/popups?

### ISSUE THREAD

**Issue by kajensen** [Boris-Em/BEMSimpleLineGraph#119]
I think it would be a good idea to have delegate methods to define a custom NSString for y-values/popups.

**Comment by kajensen** [comment]
if somebody wants my solution, its at https://github.com/kajensen/BEMSimpleLineGraph (d8f24147dae4e53ee51103e5507e8885c4844c25) ... there is now an optional delegate for y labels for value (not index!). This applies to popup labels as well, but keep in mind that there is a limited amount of space for these labels. The label shrinks to 50% size but anything with a decent amount of characters will be hard to read. Feel free to improve my solution, but this is working for me. (side note: not really sure what the popuplabel suffix method is used for, but this overrides it, check the change logs).

**Comment by Sam-Spencer** [comment]
@kajensen You should make a pull request so your changes can be discussed and then merged into the main project.

The `popupLabelSuffix` adds a suffix to a number on the pop up labels. For example, if your graph was charting miles over time, you might return a `mi` suffix. So instead of simply showing `9.0`, the label would display `9.0 mi`.

**Comment by alessign** [comment]
How can I implement string values to popUp labels from array? I have saved 3 string values in an array (min, zero, max) assigned to objectAtIndex in arrayOfValues and would like to display them in pop up labels accordingly. How do I pass the data to the method below and change the "dataPoints" array please?

if ([self.delegate respondsToSelector:@selector(popUpSuffixForlineGraph:)])
        self.popUpLabel.text = [NSString stringWithFormat:@"%li%@", (long)[dataPoints[(NSInteger) closestDot.tag - DotFirstTag100] integerValue], [self.delegate popUpSuffixForlineGraph:self]];
        
    else
        self.popUpLabel.text = [NSString stringWithFormat:@"%li", (long)[dataPoints[(NSInteger) closestDot.tag - DotFirstTag100] integerValue]];
       
Thank you for suggestions
A.

**Comment by Sam-Spencer** [comment]
@alessign Please see the README and the Wiki for instructions on using BEMSimpleLineGraph and getting your data source setup. In the future, you may also want to ask your question by opening a new issue.

**Comment by Sam-Spencer** [comment]
I am going to close this issue for now, seeing as popup suffixes are fully supported and popup prefixes are well on the way. If you're looking for something different, please let us know and we can reopen the issue.
