### ISSUE TITLE
lineGraphDidFinishLoading

### ISSUE THREAD

**Issue by GabrielByss** [Boris-Em/BEMSimpleLineGraph#124]
lineGraphDidFinishLoading delegate method is not waiting for start animation to end result is blank image when you use graphSnapshotImage in this method

**Comment by Sam-Spencer** [comment]
A new `lineGraphDidFinishDrawing:` delegate method fixes this issue. You can implement this new method in your delegate to be notified when the graph finishes drawing and animating.
