### ISSUE TITLE
popUpLabel size

### ISSUE THREAD

**Issue by alessign** [Boris-Em/BEMSimpleLineGraph#127]
Hi, I am displaying 3 different NSString values in the popUpLabels, but I couldn't find the way how to adjust it's size for static strings. These are 3x words and only 3 dots (...) are displayed instead as it is longer than popUpLabel's width. Can somebody point me towards the right direction, where to set the width please? In the init code the width is set to 100, but then it gets override somewhere...

Thank you for your time

A.

**Comment by RobDay** [comment]
Hey,

Inside of `layoutTouchReport`, the widest value is detected for all the datapoints.  Then, `sizeToFit` is called on the popupLabel. This size is then used anytime the popover use used for the current dataset.

**Comment by alessign** [comment]
Thanks, found it! I have set the maxValue and it works now

     NSString *maxValueString = [NSString stringWithFormat:@"10000000"];

Best,
a.
