### ISSUE TITLE
drawXAxis overlap calculation

### ISSUE THREAD

**Issue by mbopp** [Boris-Em/BEMSimpleLineGraph#128]
Hi Boris-Em, 

I am noticing that the function for determining when x axis labels overlap is not working as expected.  It seems to be too greedy.  I have a graph with 24 points on the x axis.  (24 hours). I am choosing to display just three x-axis labels (6am, 12pm, 6pm).  I am controlling the display of these labels in the `lineGraph:labelOnXAxisForIndex:` method.  The '12pm' label is not displaying because it is considered to be overlapping.  However there more than plenty of room to display this label. (the graph is about 320 wide). 

I am passing an empty string back from the label method when I do not want to display a label.

Is there trick to resolving this without hacking the drawXAxis method?

**Comment by Sam-Spencer** [comment]
The issue at hand was fixed in [v4.0.0](https://github.com/Boris-Em/BEMSimpleLineGraph/releases/tag/v4.0). Please refer to the changes in X-Axis behavior from that release. It seems as if this issue should have been closed with the original release, but got overlooked. It is now closed.
