### ISSUE TITLE
Not working under IOS 6.1

### ISSUE THREAD

**Issue by Chrichton** [Boris-Em/BEMSimpleLineGraph#131]
BEMSimpleLineGraphView line 605:

CGRect lRect = [labelXAxis.text boundingRectWithSize:self.viewForBaselineLayout.frame.size options:NSStringDrawingUsesLineFragmentOrigin attributes:@{NSFontAttributeName:labelXAxis.font} context:nil];

--------------

boundingRectWithSize is IOS7

**Comment by Boris-Em** [comment]
HI @Chrichton,
Thank you for opening this issue, although I invite you to see the answer to #77.
No more fixes for iOS6 will be made to support iOS6.
