### ISSUE TITLE
Popup Suffix Issue when alwaysDisplayPop enabled

### ISSUE THREAD

**Issue by pyraego** [Boris-Em/BEMSimpleLineGraph#134]
If I have `alwaysDisplayPopUpLabels` enabled the popUpSuffix method never gets fired. Is this not supported? If I turn off `alwaysDisplayPopUpLabels` the popUpSuffix method gets fired when panning on the graph. Anyway to enable this if I have the popups always showing?

    - (NSString *)popUpSuffixForlineGraph:(BEMSimpleLineGraphView *)graph;

**Comment by Sam-Spencer** [comment]
Thanks for reporting this! The latest commit includes the fix.

**Comment by pyraego** [comment]
Sure thing! Thanks for the quick fix. Amazing plugin

Any ETA on Prefix? Looking to add "$" in front of data. 

Thanks again!

**Comment by Sam-Spencer** [comment]
You're welcome! Glad I could help!

Prefixes are available in PR #132. We are currently reviewing that PR (as its quite massive). Once it's approved (in the coming days) you'll have a prefix API similar to the suffix API.
