### ISSUE TITLE
Prefixes missing when alwaysDisplayPopUpLabels = YES

### ISSUE THREAD

**Issue by pyraego** [Boris-Em/BEMSimpleLineGraph#138]
I see you pushed up a commit to include prefix's. I can't seem to get them to work. Are they still being developed? I am running off the head as of this morning.

    - (NSString *)popUpPrefixForlineGraph:(BEMSimpleLineGraphView *)graph
    {
       return @"$";
    } 

![ios simulator screen shot mar 16 2015 8 46 31 am](https://cloud.githubusercontent.com/assets/1516560/6666264/05c2ab9e-cbb9-11e4-98fd-21bfdaf4905e.png)

**Comment by Sam-Spencer** [comment]
This should be working in the latest commit (20d9253c94d219541580057dee0a09ff6a1fa090). I will push up a commit with example usage added to the sample project.

Are you sure you've got the `BEMSimpleLineGraphDelegate` hooked up correctly?

**Comment by pyraego** [comment]
Ah I found the issue. In your example you don't have "alwaysDisplayPopUpLabels" enabled. With that set to YES, the prefix's don't show.

    self.myGraph.enablePopUpReport = YES;
    self.myGraph.alwaysDisplayPopUpLabels = YES;

![ios simulator screen shot mar 17 2015 8 45 00 am](https://cloud.githubusercontent.com/assets/1516560/6687495/ea84354a-cc81-11e4-954c-df5f68b89117.png)

**Comment by pyraego** [comment]
Looks good! Thank you!
