### ISSUE TITLE
background color not changing

### ISSUE THREAD

**Issue by ilandbt** [Boris-Em/BEMSimpleLineGraph#194]
Hi,
I cant figure out how to change the background color
i call :
 self.graph.backgroundColor = UIColor.whiteColor()
and it stays blue.

any suggestions?

code:
        

    
    @IBOutlet weak var graph: BEMSimpleLineGraphView!
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
        self.graph.delegate = self
        self.graph.dataSource = self
        self.graph.enableBezierCurve = true
        self.graph.enableTouchReport = true
        self.graph.colorXaxisLabel = UIColor.whiteColor()
        self.graph.colorYaxisLabel = UIColor.whiteColor()
        self.graph.enableYAxisLabel = true
        self.graph.backgroundColor = UIColor.whiteColor()

    }

**Comment by Boris-Em** [comment]
Hi @ilandbt,
First of all I would like to encourage you to post this kind of questions directly on StackOverflow using the tag [BEMSimpleLineGraph](http://stackoverflow.com/questions/tagged/bemsimplelinegraph).
We would like to keep GitHub issues strictly for bugs, feature requests etc..
StackOverflow also has a much better re-usability than GitHub issues, meaning that it would be easier for users who run into the same problem to find a solution.
 
Regarding your issue, I think that it comes from `colorTop` and `colorBottom`. You could either set them to the color you want (white) or make sure that they are see-through. You can find out more about it [here](https://github.com/Boris-Em/BEMSimpleLineGraph/wiki/Customization).

Let us know if this helped or not, thanks!

**Comment by ilandbt** [comment]
Sorry i didn't know you have a tag in stackoverflow.
Thanks for the help works grate.

**Comment by Boris-Em** [comment]
No problem, we created the tag very recently. I'm glad you made it work.
