### ISSUE TITLE
Reference lines and labels are off

### ISSUE THREAD

**Issue by hpetersen** [Boris-Em/BEMSimpleLineGraph#196]
Dear Boris,

First of all thank you for providing us this nice library.

I have a problem with my reference lines, and my labels on the x-axis, that i really can't solve without your help. I tried looking through the source and playing around with the values but without help. 

In my attached screenshot you can see that i have 3 points in my graph, first one is 100, then 50 and last one is 10.
I have no label for the point on 100, and the reference lines should be where point 50 and 10 is located, but there not. This makes it very hard to see what date the point is at, when i add more points to the graph.

![ios simulator screen shot 03 apr 2015 13 41 41](https://cloud.githubusercontent.com/assets/1536105/6981823/6bf9cb56-da08-11e4-8143-d370d33a43e7.png)
![ios simulator screen shot 03 apr 2015 13 41 44](https://cloud.githubusercontent.com/assets/1536105/6981825/6fd89374-da08-11e4-9eb4-88c6a80ae7c2.png)

I really hope you can take a few minutes of your time to look into my problem.

Best Henrik

**Comment by Sam-Spencer** [comment]
Hi @hpetersen! First of all, your app looks beautiful!! Does this happen to be the Portfolio app featured by Apple this week :open_mouth:?

As for the issue you're having with labels on the X-Axis. It seems to be the spacing of labels on the X-Axis is a recurring issue many developers are experience. We are currently investigating a fix. I'll update this post as I find out more information and test your specific use-case.

**Comment by Sam-Spencer** [comment]
Commit 64b4fb1 should fix this issue. Let me know if the problem persists and how you like the commit. Looking forward to hearing back from you!

**Comment by hpetersen** [comment]
Hey @Sam-Spencer,

Thanks alot. Unfortunately it's not my app you see in app store featured. I never seen that app, as it's not in the danish App Store, and yes it look actually pretty similar, but function wise is it very poor, i think :)

Regarding the bug, does the commit seems to be fixing my problem. ( Sort of :) ) It's works now with 3 and 6 months but as it goes into 12 months im missing the last label. I haven't tried to look into the problem yet, but i will post it, if i find anything :)

Im very glad that you where able to come with a fix so quickly :) So cool :+1:  

![ios simulator screen shot 07 apr 2015 15 47 28](https://cloud.githubusercontent.com/assets/1536105/7024588/2cc5601a-dd3e-11e4-8260-c94e84f0acf1.png)

![ios simulator screen shot 07 apr 2015 15 47 21](https://cloud.githubusercontent.com/assets/1536105/7024593/32f141ac-dd3e-11e4-8bc3-cd8eeea3f262.png)
