### ISSUE TITLE
index value for popUpSuffixForlineGraph method

### ISSUE THREAD

**Issue by testingGit12345** [Boris-Em/BEMSimpleLineGraph#199]
How can I programatically select a point in the graph?

I am using `popUpSuffixForlineGraph:` for showing a suffix, unfortunately there is no index parameter for customization of the suffix per point.

The current work around that I have applied is with `didTouchGraphWithClosestIndex:`. On the callback of `didTouchGraphWithClosestIndex:` I update the suffix string and it gets updated automatically. The problem with this workaround is that the width of the labels are not set properly.

**Comment by Sam-Spencer** [comment]
Popup prefixes and suffixes are set for the entire graph -- there is no way to set a prefix or suffix for a specific point (it's all or nothing).

In general, a line graph shows one set of data (requiring only one suffix or prefix). That said, I cannot see a use-case for this feature. What are you using it for? Do you need plural and non-plural suffixes or were you looking for completely custom values? The project emphasizes simplicity, so I doubt custom values for each point is a feature that should be included - of course, this is open for discussion. I look forward to hearing about this!

**Comment by testingGit12345** [comment]
It would be nice if we have the capability to define custom suffix, makes the project more customisable. But can you tell me how to programatically select a data point in the graph ??

**Comment by Sam-Spencer** [comment]
There is no way to programmatically select a data point on the graph and subsequently display a custom suffix for that point. You could modify BEMSimpleLineGraphView and have it call the suffix delegate method each time a popup label is needed, however this introduces efficiency problems. Additionally, it adds a layer of complexity which is unnecessary in most, if not all use cases. This is not a feature which really adheres to the premise of the BEMSimpleLineGraph project. Unless there is further discussion on the feature, I am going to close this issue.
