### ISSUE TITLE
Axis representation wrong

### ISSUE THREAD

**Issue by pimp22** [Boris-Em/BEMSimpleLineGraph#201]
I'm using a value group which contains ints / numbers from 0-5. Yet when I enable yAxis it plots in 3 values 18, 44 and 66. I tried to manually change the return types for `calculateMin/MaxPoint`, but it didn't work nor do I think thats a good approach. Also, I don't seems to be able to see any xAxis labels with this delegate method: 

    - (NSString *)labelOnXAxisForIndex:(NSInteger)index {
        NSLog(@"inside labonxa");
        if (index == _appDelegate.UVIndexBuffer.count-1)
            return @"Time";
        else
            return @"sth";
    };

It seems that the method has been "deprecated"? (red line through method text)

Any help much appreciated. I don't know why these basic things are failing for me, the library seems very promising

**Comment by Sam-Spencer** [comment]
You are correct, `labelOnXAxisForIndex:` is deprecated, as described in the documentation:

> **DEPRECATED**. Use `lineGraph:labelOnXAxisForIndex:` instead. The string to display on the label on the X-axis at a given index. Please note that the number of strings to be returned should be equal to the number of points in the Graph.
 **Warning**: This method will be removed in the next version with breaking changes.
 **Deprecated**: Deprecated in 1.3. Use \p lineGraph:labelOnXAxisForIndex: instead.

Please use the newer method, `lineGraph:labelOnXAxisForIndex:` instead. If the problem persists let us know and we will reopen the issue.
