### ISSUE TITLE
IB Designables Error after update to 4.0

### ISSUE THREAD

**Issue by cakl** [Boris-Em/BEMSimpleLineGraph#204]
After updating to version 4.0, I get the following errors when building my project:

```
error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)
error: IB Designables: Failed to render instance of BEMSimpleLineGraphView: Failed to load designables from path (null)
```

**Comment by Boris-Em** [comment]
Hi @cakl,
Can you confirm that your project still compiles and also that you have the latest version of CocoaPods?
Thanks!

**Comment by cakl** [comment]
the project still compiles, yes. 

I updated to 4.0 on the pod version 0.36.4, thought this might be the error so I uninstalled the pod BEMSimpleLineGraph and reinstalled on cocoapods 0.37.

**Comment by Boris-Em** [comment]
And you still have the errors, right?

**Comment by cakl** [comment]
Yes, I already tried the following and have still the error:
1) remove pod from podfile
2) pod update
3) added 4.0 in podfile
4) pod update
5) cleaned and removed Derived Data

**Comment by Boris-Em** [comment]
Thanks for your feedback. It seems like a pretty common issue with CocoaPods that we haven't anticipated.
Here are some threads talking about the issue: [thread#1](https://github.com/MuscleRumble/THLabel/issues/28), [thread#2](http://stackoverflow.com/questions/28204108/ib-designables-failed-to-update-auto-layout-status-failed-to-load-designables), [thread#3](http://stackoverflow.com/questions/28204108/ib-designables-failed-to-update-auto-layout-status-failed-to-load-designables).

On the [thread#3](http://stackoverflow.com/questions/28204108/ib-designables-failed-to-update-auto-layout-status-failed-to-load-designables), there seems to be a fix. If you could give it a try and report back to us that would be great!

**Comment by cakl** [comment]
Hey Boris, as I ```use frameworks``` I get another cocoapods issue but the preview in the IB works now. So I think this works as a bugfix. Thanks a lot

**Comment by Boris-Em** [comment]
Great, thanks @cakl!
