### ISSUE TITLE
Auto Layout Issue causes white pixel line

### ISSUE THREAD

**Issue by cakl** [Boris-Em/BEMSimpleLineGraph#205]
Setting autolayout constraints (horizontal space constraints) on both sides of the linegraph leads to a small white (~1px) at the right side of the graph. 

![alt text](https://s3.amazonaws.com/f.cl.ly/items/0N1J3m2a1o2D1U2Z392u/Image%202015-05-04%20at%202.27.06%20nachm..png "Sample image")

**Comment by mbeaty** [comment]
@cakl Curious if you developed a workaround for this? I'm seeing this as well. This component just doesn't do well with auto layout. Sad, because otherwise, it's a pretty sweet component.

**Comment by cakl** [comment]
No sorry, I did not found any workaround. I'm using version 3.3 now until this autolayout issues are fixed in v4.0.

**Comment by mbeaty** [comment]
It looks like if you don't mind your x/y label axis' having the same color as the view underneath, you can set colorBackgroundXAxis and colorBackgroundYAxis to UIColor.clearColor() (I'm using Swift). That will effectively mask the problem.

**Comment by Sam-Spencer** [comment]
Is this still an issue with the latest release, v4.1.1?

**Comment by Sam-Spencer** [comment]
Thanks for pointing out this bug. I couldn't seem to replicate the issue with the instructions provided and the latest version of the project. This issue is now closed unless additional steps or clarification can be provided.
