### ISSUE TITLE
Display data for week, month and current day.

### ISSUE THREAD

**Issue by sahil263** [Boris-Em/BEMSimpleLineGraph#210]
Is there a way to display the graph data for week, month and current day from the dates supplied in "labelOnXAxisForIndex" delegate method.

For reference I have attached a screen short of the screen (what I am trying to achieve)

![graph](https://cloud.githubusercontent.com/assets/4958184/7955642/943ed38a-09f7-11e5-86f7-504442b29e2d.png)

As, you can see that at top there are 3 buttons named "day", "week" and "month".
When this screen is loaded all the data is loaded on to the graph. Now, further is it possible to reload the graph with "day", "week" or "month" data (from the data already loaded onto the graph)?

**Comment by Sam-Spencer** [comment]
You'll need to modify your own datasource and then reload the graph to accomplish this. It shouldn't be too tricky to do. If you have questions about how to do this kind of thing, please refer to the documentation in the wiki or ask a question using the BEMSimpleLineGraph tag on StackOverflow.
