### ISSUE TITLE
Clipped Y-Axis-Labels

### ISSUE THREAD

**Issue by letsbyteit** [Boris-Em/BEMSimpleLineGraph#212]
I've got some problems with my Y-Axis-Labels on iOS8. 
My y-values are like {"0.12…","0.42…","1.23…", …} and my x-values are UNIX-Timestamps. 

The problem is, the Y-Axis-Labels are clipped and just the first numbers of them are displayed. So, I expect something like {"0.1","0.4","1.2", …} but the actual result is {"0","0","1", …}.  So the decimal-places are just not visible, but some pixels of the displayed digits are also clipped! But this is just a float-thing, my integer y-values in another graph are displayed well.

Expected:
![screen shot 2015-06-15 at 00 51 32](https://cloud.githubusercontent.com/assets/7833199/8171030/2a8e9ae8-13b5-11e5-8239-958054c15797.png)

Actually:
![screen shot 2015-06-15 at 00 51 44](https://cloud.githubusercontent.com/assets/7833199/8171031/2c3c3a1c-13b5-11e5-8acf-162ca18f3543.png)

Working (integer) example:
![screen shot 2015-06-15 at 23 23 22](https://cloud.githubusercontent.com/assets/7833199/8171091/a210b862-13b5-11e5-901b-e4537ad502a4.png)

Maybe it's related to AutoLayout or something similar about my project, because your sample performs well with these y-values.

BTW: Just another question, can I adjust the X-Axis-Labels' placement? Because I might have values above 0 only and then it just looks like they're displaced at all.
BTW2: What's the recommended way to display units for y-values?

Thanks for this great library!

**Comment by Boris-Em** [comment]
Hi @letsbyteit,
Sorry for getting back to you so late...

To display decimals on the Y-Axis value, I would use the property `formatStringForValues`.
For example, in your case, I would set it to `@"%.1f"`, to display one decimal.
```
self.lineGraph.formatStringForValues = @"%.1f";
```

There does seem to be a slight truncation of the labels on the Y-Axis. Good catch! I will investigate more on that issue. 

What kind of adjustment do you exactly need to do for your X-Axis labels?

To display units for the Y-Axis labels, I would use the delegate methods `yAxisSuffixOnLineGraph:` and `yAxisPrefixOnLineGraph:`.

**Comment by Sam-Spencer** [comment]
This issue seems to have been fixed and will now be closed.
