### ISSUE TITLE
Two-finger touch reporting

### ISSUE THREAD

**Issue by the3rdshed** [Boris-Em/BEMSimpleLineGraph#213]
Similar to the Apple Stocks app, it would be great to be able to be able to use 2 fingers for touch reporting to allow for comparing values.

**Comment by Sam-Spencer** [comment]
This is quite a complex undertaking. If anyone would like to tackle this in a pull request, it would be greatly appreciated.

**Comment by Sam-Spencer** [comment]
Due to the similarity and extended discussion of this, and similar requests, on #235, this issue will now be closed. All further discussion should be directed to Issue #235.
