### ISSUE TITLE
Gaps between dates

### ISSUE THREAD

**Issue by cujo30227** [Boris-Em/BEMSimpleLineGraph#217]
I'm using BEMSimpleLineGraph to plot a series a values as function of dates. The dates are not always sequential, but BEMSimpleLineGraph still shows them as sequential. For example, datapoints for June 9th and June 15th (6 days apart) have the same horizontal distance as data points for June 15th and June 16th (1 day apart). I have two questions:  
 1. Is there a way to respect the actual dates and show the data points with a separation distance which is proportional with the number of days between the data points?  
 2. When I have two data points at the same date, the also show sequentially now.. Any way to show them at the same X position ? 

Thanks in advance!

**Comment by Sam-Spencer** [comment]
The solution to your first question is the use of `BEMNullGraphValue` which allows you to specify a null value for a point on the x-axis. Thus, you can add five null points between June 9 and June 15, displaying a space on the graph.

Unfortunately, your second question involves a more complex solution that BEMSimpleLineGraph just isn't equipped to handle. Multiple y-values at one x-value means the graph would no longer be a function, and BEMSimpleLineGraph deals in functions so this just isn't possible.
