### ISSUE TITLE
Is it possible to add Zoom in Zoom out?

### ISSUE THREAD

**Issue by Nandulucky** [Boris-Em/BEMSimpleLineGraph#231]
Thanks , I had done the line graph using this sample. But i need to apply zoom in zoom out of simple line graph. Is it possible to add zoom in zoom out?

Thanks in Advance.

**Comment by Boris-Em** [comment]
Hi @Nandulucky, zooming in and out is currently not supported by BEMSimpleLineGraph.
This is currently not a priority, which means that you shouldn't expect to see it implemented anytime soon.
I invite you to take a look at the project's [road map](https://github.com/Boris-Em/BEMSimpleLineGraph/wiki/Roadmap) to have a better understanding of where the project is headed.
Having said that, I would like to encourage you to work on this feature if you can, as it would be a great addition to the library!
