### ISSUE TITLE
Wrong Bezier curve when 2 data points

### ISSUE THREAD

**Issue by J-Crichton** [Boris-Em/BEMSimpleLineGraph#233]
When Bezier is enabled and graph has only 2 data points - graph is curved bur line is stright.
![2015-09-13 23-18-02 ios simulator - iphone 6 plus - iphone 6 plus ios 8 4 12h141](https://cloud.githubusercontent.com/assets/10173008/9848797/2a54bd4e-5aed-11e5-8a05-fb6275a39a5a.png)

Workaround is like this:

self.simpleLineGraph.enableBezierCurve = numberOfDataPoints > 2;

But please consider to resolve this on your side.

**Comment by dagobert-duck** [comment]
+1

**Comment by Sam-Spencer** [comment]
Most recent commits should fix this issue from within the project, no changes needed on your end. Enjoy!
