### ISSUE TITLE
Tap to refresh

### ISSUE THREAD

**Issue by 99centsappdevelopment** [Boris-Em/BEMSimpleLineGraph#234]
Is it possible to disable the tap to refresh feature (i.e, when I tap on the graph, it reloads all data)?

**Comment by Boris-Em** [comment]
Hi @99centsappdevelopment, the graph shouldn't reload when you tap on it.
Could you describe the behavior a little bit more? Thank you!

**Comment by Sam-Spencer** [comment]
Seeing as there is no tap to refresh feature, I am going to close this issue unless there is further discussion.
