### ISSUE TITLE
Labels and popups not working for more than two data points

### ISSUE THREAD

**Issue by danielbmarques** [Boris-Em/BEMSimpleLineGraph#237]
On my swift project when I have only two data points everything works as expected, but if I add more than two the labels won't show for the x axis and popups won't work either, and that's just what I tested, I suspect there are other problems too.
At first I thought this was related to having a separate delegate, which is necessary to add the x axis label method, but apparently that has nothing to do with it. Any ideas about what could be causing this?

**Comment by Sam-Spencer** [comment]
Could you provide the exact steps needed to replicate this issue? I can't seem to replicate it...

**Comment by danielbmarques** [comment]
I tried it again with the latest commit to the feature branch and it's all working. I guess I must have broken something when trying to fix the deprecated methods in earlier commits.
Thank you for the great work here. :)

**Comment by Boris-Em** [comment]
Thanks for your feedback @danielbmarques!
