### ISSUE TITLE
Problem with bottomcolor / missing fillcolor property

### ISSUE THREAD

**Issue by skuske** [Boris-Em/BEMSimpleLineGraph#238]
I cannot find a graph 'fillcolor' property.

Problem is: the bottomcolor property makes the graph look extremely unprofessional, as it fills the area below the graph's line as well as the area below the x-axis. There should be a separate 'fillcolor' property, which fills the area below the graph's line and the x-axis line.

Maybe I missed something, but I cannot find a way to only fill the area between the graph's line and the x-axis line... I mrked that area red:

![1111](https://cloud.githubusercontent.com/assets/12996815/11584199/4285de16-9a62-11e5-8001-da80f4fa15f6.png)

Currently it looks like this:

![image1](https://cloud.githubusercontent.com/assets/12996815/11584070/e28115a4-9a60-11e5-8383-58191c6bc89e.PNG)

**Comment by Sam-Spencer** [comment]
Did you find a solution to this? I believe the `colorBackgroundXaxis` property may be what you're looking for.

**Comment by skuske** [comment]
Yes, that's what I was looking for. Found it 2 minutes after submitting
the issue... :) Sorry for the trouble. 

Stefan 

Am 04.12.2015 17:48, schrieb Sam Spencer: 

> Did you find a solution to this? I believe the `colorBackgroundXaxis` property may be what you're looking for.
> 
>> On Dec 4, 2015, at 3:09 AM, skuske <notifications@github.com> wrote:
>> 
>> Closed #238.
>> 
>> --
>> Reply to this email directly or view it on GitHub.
>> 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/Boris-Em/BEMSimpleLineGraph/issues/238#issuecomment-162017365
