### ISSUE TITLE
alwaysDisplayPopUpLabels only displays the first value

### ISSUE THREAD

**Issue by rfunk82** [Boris-Em/BEMSimpleLineGraph#243]
alwaysDisplayPopUpLabels is only displaying the first value instead of the 5 plotted points, I can see the points but not the values.

**Comment by Sam-Spencer** [comment]
I can't seem to replicate this issue with either v4.1.1 or the current build on the master branch (see below, it seems to be working fine). Could you please provide additional details and steps to replicate? 

![simulator screen shot feb 21 2016 2 50 53 pm](https://cloud.githubusercontent.com/assets/2374407/13204976/8524bbe4-d8aa-11e5-9ba0-341285130745.png)
