### ISSUE TITLE
reloadGraph takes a long time to load the graph (about 15 seconds)

### ISSUE THREAD

**Issue by rfunk82** [Boris-Em/BEMSimpleLineGraph#244]
reloadGraph takes a long time to load the graph (about 15 seconds). and this is only plotting 5 points.

**Comment by Boris-Em** [comment]
Hi @rfunk82, 
Are you sure that you're on the main thread when calling`reloadGraph`?

**Comment by Sam-Spencer** [comment]
The project's unit tests report that the graph loads 100 data points in 0.012 seconds (on average). Could you provide steps to replicate this issue?
