### ISSUE TITLE
We are using your great line graphing code - Thanks!

### ISSUE THREAD

**Issue by qapps** [Boris-Em/BEMSimpleLineGraph#245]
Please consider adding our app CostLog to your Wiki. We have chosen to use your BEMSimpleLineGraph CocoaPod because it most closely matched our requirements:

CostLog (FREE) - https://itunes.apple.com/us/app/id965047409

CostLog is a simple, yet powerful App to truly help manage Personal budget (or even the entire Household budget now since v1.3). Time has come to stop tracking how much has been on your accounts and look forward to see what is possible with a future budget... Always free with no Ads (donationware) ~ brought to you by QApps.co

**Comment by Boris-Em** [comment]
Hi @qapps,
Thank you for letting us know! Your app has been added to the wiki. Great job on the CostLog by the way!
