### ISSUE TITLE
Reference lines above chart

### ISSUE THREAD

**Issue by pacosta** [Boris-Em/BEMSimpleLineGraph#247]
The reference lines appear above the chart and I want them to go behind the chart.
Is there a way to do this??

![screen shot 2016-01-07 at 18 09 17](https://cloud.githubusercontent.com/assets/456403/12178522/cfcb712e-b569-11e5-817a-fcc3882e0783.png)

**Comment by Sam-Spencer** [comment]
Issue #75 requested this same feature originally as early as 2014. It has been added to a milestone and is slated for a future release of the project. Closing this issue as a duplicate.
