### ISSUE TITLE
Labels on YAxis

### ISSUE THREAD

**Issue by Joanii** [Boris-Em/BEMSimpleLineGraph#253]
I want to add different labels on YAxix, depending on values . For example: for the (values < 1) I want to add the label "Small", for 1< values <= 2 add the label "Medium" and for (values  > 2) add the label "Big".
Can I do that with BEMSimpleLineGraph?

**Comment by Boris-Em** [comment]
Hi @Joanii,
No, unfortunately BEMSimpleLineGraph doesn't offer this kind of customization for the Y-Axis labels.
Let me know if you would be interested in contributing to the project to add this feature.

Thanks,

Boris.

**Comment by Joanii** [comment]
I am interested contributing to the project to add that feature :+1:
