### ISSUE TITLE
I have problem,help me!!!

### ISSUE THREAD

**Issue by ganjmeng** [Boris-Em/BEMSimpleLineGraph#265]
hi Boris

The BEMSimpleLineGraph is the really good, I used it in my task.
I have a problem that how I can show the border line in the `XAxis and YAxis`, and how I can set the `XAxis labels` background color Like The `Yaxis`(XAxis Labels background color is Like The colorBottom but I want to set is clear or white).

I'm sorry about that my English is really pool, I hope you can understand what I said....
![image](https://cloud.githubusercontent.com/assets/12026835/15996213/b941bc46-3157-11e6-9966-7ad09ade8562.png)

**Comment by ganjmeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12026835/15996410/af74384a-3159-11e6-96b0-915b063ddb08.png)
I found how to set border!!!  how ti set XAxis Labels background color??

**Comment by ganjmeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12026835/15996464/25cdcb3c-315a-11e6-89ac-f2efe0859646.png)
Perfect! I have solved that!😎

**Comment by Boris-Em** [comment]
Closed as fixed.
