### ISSUE TITLE
Partial X-Axis, Partially Filled Graph

### ISSUE THREAD

**Issue by FrederickGeek8** [Boris-Em/BEMSimpleLineGraph#27]
If you are looking for new features to implement, a feature I would like is the ability to set a static value for the x-axis maximum and x-axis label, so if there is not enough entries to fill the graph, you will see a partially filled graph.

**Comment by Sam-Spencer** [comment]
Considering version 4.0 now allows you to specify NULL values, this feature, in a way, is implemented. I believe that the goal which you're looking for here can now be achieved. If this is not the case, let us know, and we'll reopen the issue. :+1:
