### ISSUE TITLE
How to change colour of graph in a particular area?

### ISSUE THREAD

**Issue by bibinkonankunju** [Boris-Em/BEMSimpleLineGraph#270]
Hi,
I want to change the graph colour in some selected areas. Means, currently my graph colour is blue, and from x-axis point 5 to  point 10, I want to make it green colour. The rest of the other graph areas should be in blue colour only. How can i do this?

**Comment by Boris-Em** [comment]
Hi @bibinkonankunju,
You can customize the color of the top and bottom part of the graph.
See the [wiki](https://github.com/Boris-Em/BEMSimpleLineGraph/wiki/Customization).

**Comment by bibinkonankunju** [comment]
![screen shot 2016-08-29 at 12 41 21 pm](https://cloud.githubusercontent.com/assets/19684469/18043510/f0eb646a-6de5-11e6-8ffe-2fcaa7221fd4.png)

**Comment by Sam-Spencer** [comment]
Hi @bibinkonankunju, this feature is not currently supported in the library. It may be implemented in a future release. Until that time, I would suggest taking a look at the `BEMLine` class and modifying it to suit your specific needs. If you are able to make those changes, a pull request would be appreciated.
