### ISSUE TITLE
When points count > 900 xAxis Labels can't show  Total labels,and The line can't drag to rightmost

### ISSUE THREAD

**Issue by ganjmeng** [Boris-Em/BEMSimpleLineGraph#272]
When points count > 900 xAxis Labels can't show  Total labels,and The line can't drag to rightmost

![image](https://cloud.githubusercontent.com/assets/12026835/18162644/d8065c3a-7069-11e6-9920-446ed9730002.png)

**Comment by Boris-Em** [comment]
This seems like a dup of #203. 
@ganjmeng, please reopen this bug if you believe that I'm wrong.
Anyway, thank you for your contribution!
