### ISSUE TITLE
Multiline Support

### ISSUE THREAD

**Issue by GopiK14** [Boris-Em/BEMSimpleLineGraph#273]
Is this possible to create Multiline ? Any update on new feature? Also Please confirm this commit will work for more lines https://github.com/Boris-Em/BEMSimpleLineGraph/pull/133/commits/4dd3eb085dfa36fd574526b57209db78deb3f768#diff-9a7f9697a15db8d1332c234d7877cd39

Thanks!

**Comment by xumoyan** [comment]
Your revised version and do not match the version now...

**Comment by GopiK14** [comment]
Thanks!! It would be good if you have any solution or tutorials ?

**Comment by Sam-Spencer** [comment]
Your contribution is appreciated, however this issue will now be closed as a duplicate of #44. Should there be more specific updates to or questions related to this issue, it can be reopened. Thank you.
