### ISSUE TITLE
We are using your great line graphing code - Thanks!

### ISSUE THREAD

**Issue by skg54** [Boris-Em/BEMSimpleLineGraph#279]
FishHawk is a location-based social network and utility for anglers. It allows users to share photos/videos and see what people are catching in their area. Integrated into the app is also other useful information related to fishing. The tides feature includes 7-day tides/solunar data for North America. I enhanced the tides screen UI for the latest update (pending) using the BEMSimpleLineGraph Library to visualize the tide events for each day. It makes the information much easier to understand and digest compared to tabular data.

Please consider adding my app FishHawk to your Wiki.

[https://itunes.apple.com/us/app/fishhawk/id474655362](https://itunes.apple.com/us/app/fishhawk/id474655362)

![img_2642](https://cloud.githubusercontent.com/assets/942814/19469325/dbe470aa-94e8-11e6-94bc-05cde24c8d1d.jpg)

**Comment by Boris-Em** [comment]
Great! Thanks for letting us know =D
I will update the wiki page with your app.
