### ISSUE TITLE
Scaling the values on y-axis

### ISSUE THREAD

**Issue by Venkata-Maniteja** [Boris-Em/BEMSimpleLineGraph#284]
I'm trying to place two graphs one on one. And trying to plot 7 values.
One plots the values that are in the range:

<__NSArrayM 0x17405dfd0>(
50010.95890410959,
50021.91780821918,
50032.87671232877,
50043.83561643836,
50054.79452054795,
50065.75342465754,
50076.71232876712
)

Another one values are:

<__NSArrayM 0x17025bf60>(
49466.9,
0,
0,
0,
0,
0,
0
)

**Graph 1 :** Values start from 50,010 and increases and the final value is 50,076
Here I think the graph seems to plot it correctly. There is a line which is drawn according to the values. The lowest value (50,010) is drawn at the bottom of the screen near to the origin.

**Graph 2 :** Values start from 49,466 and all the other values are 0
Here I think the graph seems to plot it wrongly. There is a line which is drawn according to the values. Here the first value (49,466) is drawn at the top of the screen.

Why is it happening ?

I think, the value in graph 2 (49,466) should be plotted  very near to value (50,010) in graph 1.

![fullsizerender-3](https://cloud.githubusercontent.com/assets/6621259/20044118/14e71774-a464-11e6-9581-f26413c909cb.jpg)

The light blue line is of graph1, and dark line is of graph 2.As you can see, the graph1 values are plotted correctly as per the value. But the dark blue line graph is not correct.

**Comment by Boris-Em** [comment]
This behavior seems correct to me.
On the first graph, the lower part of the Y axis represents 50010, and the top part of the Y axis represents 50076.
On the second graph, the lower part of the Y axis represents 0, and the top part of the Y axis represents 49466.
Basically, the Y axis of the two graphs are not the same.

By default, the bottom of the Y axis will be the smallest value, and the top of the Y axis will be the biggest value.

**Comment by Venkata-Maniteja** [comment]
Thanks for clarifying the logic. I thought the graph is plotted according to the values in the array by following the exact order in the array.
