### ISSUE TITLE
Add multiples lines on Graph.?

### ISSUE THREAD

**Issue by meetdoshi1992** [Boris-Em/BEMSimpleLineGraph#290]
How can I add multiple lines on the Graph.?

I want to show 4 lines on the graph. And want to show hide as well. How can I do that using this graph.?

Is this possible for this graph.?

Thanks,
Meet.

**Comment by Boris-Em** [comment]
Hi @meetdoshi1992,
Thank you for opening this issue. **BEMSimpleLineGraph** currently doesn't support multiple lines. See #44 for more information about this feature.
Closing as duplicate.
