### ISSUE TITLE
Unavailable some functions after migrating to swift 3

### ISSUE THREAD

**Issue by anirudhamahale** [Boris-Em/BEMSimpleLineGraph#297]
I am using BEMSimpleLineGraph (4.1) after migrating from swift 2.3 to swift 3 it gives the below error
![screen shot 2017-04-04 at 11 15 05 am](https://cloud.githubusercontent.com/assets/16848003/24643001/a6465ec6-1928-11e7-9eae-b6c77f2d06eb.png)

How do I solve this issue?

**Comment by anirudhamahale** [comment]
I found the solution for this, don't confirm to delegate, for more info see this [#214](https://github.com/Boris-Em/BEMSimpleLineGraph/issues/214)

**Comment by Sam-Spencer** [comment]
@anirudhamahale If a method "has been marked unavailable" that means it is still defined but is, well, no longer available for use. In this case, implementing those methods will have no effect and they will not be called. Check the header for the new methods to implement.
