### ISSUE TITLE
Add option to draw an "average" line

### ISSUE THREAD

**Issue by AskinOharis** [Boris-Em/BEMSimpleLineGraph#42]
First, a big thanks for this great lib... helps a lot!!

I would be nice to have the option to draw a "average" line (average value from all data values) in a different color.

**Comment by Sam-Spencer** [comment]
Average lines are finally here!! Use the new `averageLine` property on BEMSimpleLineGraph to setup and draw an average line. Trend lines are still not available, but are definitely planned.

More documentation is coming soon on average lines (the implementation is an approach brand-new to BEMSimpleLineGraph), but the sample app should have sufficient explanation at the moment.

Cheers! :tada:

**Comment by emergencyhug** [comment]
AverageLine not found in BEMSimpleLineGraph(ver 3.3) which was installed via Cocoapods:
![cocoapods](https://cloud.githubusercontent.com/assets/11552626/7386735/ac73c052-ee89-11e4-87c1-52f12aa43c32.png)
 but found in which was downloaded directly from Github:
![clone](https://cloud.githubusercontent.com/assets/11552626/7386739/b3d0005e-ee89-11e4-86cf-3061cf28da3c.png)
Please help Checking.

**Comment by Sam-Spencer** [comment]
@emergencyhug  Version 4.0 has finally been released and is now available on Cocoa Pods.

**Comment by Sam-Spencer** [comment]
Additionally, because this issue has been resolved in v4.0 with the addition of an average line (which is what the original post requested), this issue will be closed. If you would like to see a trend line added to the project, please open a new issue.
