### ISSUE TITLE
Y-Axis zero value not aligned at graph origin

### ISSUE THREAD

**Issue by Sam-Spencer** [Boris-Em/BEMSimpleLineGraph#49]
When drawing a graph the Y-Axis zero value appears above the origin of the graph. The coordinate (0, 0) should be in the lower left corner of the graph. However, it appears above the X-Axis at a seemingly arbitrary value such as  (0, 10).

![ios simulator screen shot jul 2 2014 10 33 37 pm](https://cloud.githubusercontent.com/assets/2374407/3464978/3559b104-025b-11e4-80e1-a011745ba814.png)

My guess is that this is a padding / calculation issue.

**Comment by tdunham02** [comment]
How can we remove the padding if we don't use a line with bezier curve?

**Comment by tdunham02** [comment]
If anyone else finds this and is curious, this is what works for me (might vary with size of graph)....

In the `- (CGFloat)yPositionForDotValue:(CGFloat)dotValue` method, on the first few lines, it sets the padding according to the frame height divided by 2. I manually set the padding value to `15` and that aligns at the bottom.

**Comment by RyPoints** [comment]
Thanks tdunham02, very helpful!

**Comment by devpascoe** [comment]
found this delegate method...

- (CGFloat)staticPaddingForLineGraph:(BEMSimpleLineGraphView *)graph {
    return 0;
}

**Comment by devpascoe** [comment]
update, I had to revert to the previous version ...
pod 'BEMSimpleLineGraph', '3.3'

and apply that above method to get each top right and bottom left points to kill the padding. I believe the new version may have broken something.
