### ISSUE TITLE
Just Dots; No Line

### ISSUE THREAD

**Issue by mythodeia** [Boris-Em/BEMSimpleLineGraph#51]
Hello @Boris-Em, Thanks for sharing this excellent control.

Another great feature for this which would be easy to implement, is to allow the user to show/hide the bezier completely and just show the dots. What do you think?

**Comment by Sam-Spencer** [comment]
This feature has finally been added! Thanks for the suggestion. I hope you enjoy using the new `displayDotsOnly` property on **BEMSimpleLineGraph**.

**Comment by mythodeia** [comment]
Thanks for adding it.will do some tests tomorrow

**Comment by mythodeia** [comment]
@Sam-Spencer one question. When i enable the dots only option can i make the curves behind disappear? i only want to show the dots.

**Comment by Sam-Spencer** [comment]
You can customize the graph as you would normally do so. I'm not exactly sure what you mean by curve? 

I'm assuming you have a different color / gradient set for the bottom or top of the graph and there appears to be a curve? If that's the case, just set the bottom and top portions to the same color or gradient.

**Comment by mythodeia** [comment]
@Sam-Spencer 
the following screenshot will show you how the chart is showing when topColor & bottomColor are the same
I have commented out the gradientBottom & gradientTop. Even if i make them the same too it shows worse.
![issue](https://cloud.githubusercontent.com/assets/1748458/7082422/960d5684-df5c-11e4-8f7f-85168c8b9d15.png)

**Comment by Sam-Spencer** [comment]
I'm not sure what exactly is going on there. Are you able to replicate this issue in the Sample App?

**Comment by mythodeia** [comment]
yes..thats from the sample app
