### ISSUE TITLE
Y-axis label issues

### ISSUE THREAD

**Issue by kajensen** [Boris-Em/BEMSimpleLineGraph#62]
The x-axis labels currently show up below the frame and the background is the `color/alphaBottom`. This is not the same for the y-axis. The background is the `backgroundColor`. This can be avoided by making the background a solid color, but any other styling will get you in trouble. The example looks fine, but a white backgroundColor with different alpha top/bottom has issues (that i'm currently experiencing).

Additionally, some y-axis labels are cutoff and only display "...". Personally, I would like to see this as just a smaller font if it cannot fit.

A way to avoid the above issues all together would to have the y-axis labels appear inside the graph's frame (with the y-axis). This would be the best solution to me.

**Comment by Supertecnoboff** [comment]
I had to set the following property, in order for the y axis labels to fit properly on screen:

```[labelYAxis setAdjustsFontSizeToFitWidth:YES];```
