### ISSUE TITLE
'numberOfXAxisLabelsOnLineGraph' instead of 'numberOfGapsBetweenLabelsOnLineGraph'?

### ISSUE THREAD

**Issue by kajensen** [Boris-Em/BEMSimpleLineGraph#66]
I think it would be better to have the option to specify the number of labels on x axis (just like y...evenly distributed with max/min/x number in-between) as opposed to the gaps.

**Comment by dbrownstone** [comment]
If I understand this correctly, this is only partly answered. The other side of the coin is if you have to many points, there may not be any room to fit the labels in - there should be a way to say something like "show every 10th y-axis reference line or something like that

**Comment by Sam-Spencer** [comment]
Version 4.0 did a lot of work to improve the behavior of x-axis labels. Further changes to the underlying structure / layout of the x-axis labels are not an emphasis for this project currently. Considering the behavior and customization ability, I am going to close this issue.
