### ISSUE TITLE
Making the end-user aware that the graph is interactive.

### ISSUE THREAD

**Issue by Boris-Em** [Boris-Em/BEMSimpleLineGraph#68]
<i>Please see issues #59 and #65.</i>

Currently it seems like a lot of end-users do not realize that the graphs created with <b>BEMSimpleLineGraph</b> are [interactive](https://github.com/Boris-Em/BEMSimpleLineGraph/wiki/Touch-Reporting-%28Interactive-Graph%29).

As suggested in the issue #59, making the graph react on touch-down (and not when the drag starts) would improve the discoverability of this feature.

As suggested in the issue #65, displaying an [image](http://icons8.com/icons/#!/868/nui2) would make the end-user understand that he can touch the graph.

On a same note, adding a label (<i>"Drag your finger along the graph to see its data"</i>) on top of the graph that disappears once the user touches it would provide the same benefit.

All of these features should of course be optional and by default, none of them should be displayed.

**Comment by bryandunbar** [comment]
I have implemented this, with a simple tapGesture and a couple of small changes to the pan gesture recognizer. I'll submit a pull request this week.

**Comment by Sam-Spencer** [comment]
Pull Request #129 changes the touch behavior of the graph so that the interactivity starts when touches begin rather than when a pan gesture begins.

**Comment by Sam-Spencer** [comment]
Should now be fixed with the implementation of the long press gesture on the graph.

**Comment by Sam-Spencer** [comment]
With the release of version 4.0 and the new features it brings, I believe this issue has been resolved :checkered_flag:. If you believe this issue should be reopened, let's have a discussion!
