### ISSUE TITLE
Crashed in iOS 6 using iOS 7+ selector

### ISSUE THREAD

**Issue by lldld** [Boris-Em/BEMSimpleLineGraph#77]
@selector boundingRectWithSize:options:attributes:context: and sizeWithAttributes: for NSString in iOS6 crashed.

Change to below:

       if ([longestLabel.text respondsToSelector:@selector(sizeWithAttributes:)]) {
            NSDictionary *attributes = @{NSFontAttributeName: self.labelFont};
            labelYaxisOffset = [longestLabel.text sizeWithAttributes:attributes].width + 5;
        }
        else{
            labelYaxisOffset = [longestLabel.text sizeWithFont:self.labelFont].width + 5;
        }

and 

               CGRect lRect = CGRectZero;
                if ([labelXAxis.text respondsToSelector:@selector(boundingRectWithSize:options:attributes:context:)]) {
                    lRect = [labelXAxis.text boundingRectWithSize:self.viewForBaselineLayout.frame.size options:NSStringDrawingUsesLineFragmentOrigin attributes:@{NSFontAttributeName:labelXAxis.font} context:nil];
                }
                else{
                    lRect.size = [labelXAxis.text sizeWithFont:labelXAxis.font constrainedToSize:self.viewForBaselineLayout.frame.size lineBreakMode:NSLineBreakByWordWrapping];
                }

**Comment by Sam-Spencer** [comment]
Hi @lldld! Once again, thanks for reporting this issue. However, as of February 22, 2015 over 92% of iOS devices are running iOS 7 or iOS 8. A very small percentage are running iOS 6 or lower, and with that no more updates for iOS 6 or lower will be pushed to BEMSimpleLineGraph.

If you need to make compatibility changes for older iOS versions, I would recommend doing so on a per project basis as needed.
