### ISSUE TITLE
Ability to draw lines with negative values

### ISSUE THREAD

**Issue by skywinder** [Boris-Em/BEMSimpleLineGraph#82]
Is it possible to implement something like this:
![screen shot 2014-05-08 at 00 40 54](https://cloud.githubusercontent.com/assets/3356474/2909235/9437c104-d630-11e3-8b94-6592ef9135a0.png)

**Comment by Sam-Spencer** [comment]
As of PR #83, negative values in the graph are officially supported. Because this feature has been implemented, this issue will be closed. If you would like additional features or enhancements for negative values, open a new issue.

**Comment by skywinder** [comment]
@Sam-Spencer I'm not clear define what I mean
But it's not related with #86.
This feature-request about fill negative values with another color (like on the picture above).
