### ISSUE TITLE
Y labels drawn off of graph

### ISSUE THREAD

**Issue by sdupuis1** [Boris-Em/BEMSimpleLineGraph#95]
The calculation for yPositionForDotValue is incorrect, when autoScaleYAxis is on, the calculation works ok for larger values, but as an example use 0.5,1,2 as the Y axis points. This results in y positions larger than the view height. So the labels get drawn outside the linegraphview CGrect.

**Comment by Sam-Spencer** [comment]
In recent commits and pull requests (specifically 6a7c223a342edd842fe9076558d1b34a6e8044ba) this issue should be fixed. If the problem persists, please let us know and I can reopen the issue.
