### ISSUE TITLE
labelOnXAxisForIndex issue

### ISSUE THREAD

**Issue by rentisdue** [Boris-Em/BEMSimpleLineGraph#96]
Hello! First off great library!
I have an issue that I am struggling with a bit.  Here is a rundown of what I am trying to accomplish:
I have a large incoming data set lets say an example set would contain 160 or so items.  These values are distributed among 3 dates, and I determine how many value points are associated with a particular date.  What I would like to accomplish is to present a date label at what will be the equivalent of midnight in my dataset displayed on the X axis.  If possible it would also be nice to place a tic mark half-way between the labels.  I am attempting to present a label at a particular index in - (NSString *)lineGraph:(BEMSimpleLineGraphView *)graph labelOnXAxisForIndex:(NSInteger)index;
Unfortunately when I pass labels for specific indexes they do not appear. Any thoughts? Thanks!

**Comment by Sam-Spencer** [comment]
We would like to encourage you to post this kind of question directly on StackOverflow using the [BEMSimpleLineGraph tag](http://stackoverflow.com/questions/tagged/bemsimplelinegraph).

We would like to keep GitHub issues strictly for bugs, feature requests, enhancements, etc. StackOverflow also has a higher discoverability and re-usability than GitHub issues, meaning that it would be easier for users who run into the same problem to find a solution.

In fact, you can [ask your question right here](http://stackoverflow.com/questions/ask). Make sure to add the correct tags.
